2021-06-23 19:13:18,383 ERROR: Exception on /reset_password_request [POST] [in /home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dell/Documents/microblog/app/routes.py", line 177, in reset_password_request
    send_password_reset_email(user)
TypeError: send_password_reset_email() takes no arguments
2021-06-23 19:17:01,941 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 20:18:37,712 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:46]
2021-06-23 20:18:50,685 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:46]
2021-06-23 20:19:28,250 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 20:19:36,291 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 20:44:21,418 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 20:45:27,630 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 20:52:07,749 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 20:56:10,161 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 21:09:13,737 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 21:10:29,556 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 21:29:01,294 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 21:34:22,974 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 21:34:34,578 ERROR: Exception on /reset_password_request [POST] [in /home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dell/Documents/microblog/app/routes.py", line 177, in reset_password_request
    send_password_reset_email(user)
  File "/home/dell/Documents/microblog/app/email.py", line 21, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
TypeError: send_email() got an unexpected keyword argument 'text_html'
2021-06-23 21:36:47,097 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 21:37:23,834 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 21:38:11,100 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
2021-06-23 21:40:50,245 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:47]
