2021-06-22 23:19:18,066 ERROR: Exception on /user/user1 [GET] [in /home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/dell/Documents/microblog/app/routes.py", line 78, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dell/Documents/microblog/app/templates/user.html", line 28, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-06-22 23:21:23,818 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:10:38,225 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:11:09,125 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:23:58,245 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:33:34,161 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:42:50,263 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
